<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>mql.output</string>
        <key>name</key>
        <string>mql-output</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>"(.*?)"</string>
                <key>name</key>
                <string>string.quoted</string>
            </dict>
            <dict>
                <key>match</key>
                <string>'(.*?)'</string>
                <key>name</key>
                <string>string.quoted</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b\d+\.?\d*?\b</string>
                <key>name</key>
                <string>constant.numeric</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(([a-z]|[0-9]|[_|-])*(\.([a-z]|[0-9]|[_|-])*)+))\b</string>
                <key>name</key>
                <string>support.type</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(?<=\[Done\])(.+)</string>
                <key>name</key>
                <string>token.done.mql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(\[Done\])</string>
                <key>name</key>
                <string>token.heading.mql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(?<=\[Warning\])(.+)</string>
                <key>name</key>
                <string>token.warning.mql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(\[Warning\])</string>
                <key>name</key>
                <string>token.heading.mql</string>
            </dict>
             <dict>
                <key>match</key>
                <string>(?<=\[Starting\])(.+)</string>
                <key>name</key>
                <string>token.done.mql</string>
            </dict>
             <dict>
                <key>match</key>
                <string>(\[Starting\])</string>
                <key>name</key>
                <string>token.heading.mql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(?<=\[Error\])(.+)</string>
                <key>name</key>
                <string>token.error.mql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(\[Error\])</string>
                <key>name</key>
                <string>token.heading.mql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(?<=\[Info\])(.+)</string>
                <key>name</key>
                <string>token.info.mql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(\[Info\])</string>
                <key>name</key>
                <string>token.heading.mql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(Info))(\:|\b)</string>
                <key>name</key>
                <string>token.info.mql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\berror+(?!\:)\b</string>
                <key>name</key>
                <string>token.error.mql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(warning))(\:|\b)</string>
                <key>name</key>
                <string>token.warning.mql</string>
            </dict>
            <dict>
                <key>match</key>
                <string>([a-zA-Z]+:\\.+(?= :))</string>
                <key>name</key>
                <string>storage</string>
            </dict>
        </array>
    </dict>
</plist>